#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyOApp.Android.Resource", IsApplication=true)]

namespace MyOApp.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Refractored.MvxPlugins.Settings.Droid.Resource.String.ApplicationName = global::MyOApp.Android.Resource.String.ApplicationName;
			global::Refractored.MvxPlugins.Settings.Droid.Resource.String.Hello = global::MyOApp.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int checkBoxEventSelected = 2131034127;
			
			// aapt resource value: 0x7f050016
			public const int eventsListView = 2131034134;
			
			// aapt resource value: 0x7f050006
			public const int labelDate = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int labelDateLabel = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int labelEventName = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int labelEventRow2 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int labelEventRow3 = 2131034133;
			
			// aapt resource value: 0x7f050009
			public const int labelLocation = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int labelLocationLabel = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int labelMap = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int labelMapLabel = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int labelOrganisator = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int labelOrganisatorLabel = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int tableLayout1 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int tableRow1 = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int tableRow2 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int tableRow3 = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int tableViewSub1 = 2131034128;
			
			// aapt resource value: 0x7f050004
			public const int trDate = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int trLocation = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int trMap = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int trOrganisator = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EventDetailView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EventListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventListView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FirstView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MapsListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MapsListView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SplashScreen = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int DetailLabel = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int LightTheme = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int TableRowLarge = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
